"""Add sesso field to guests table

Revision ID: 22feb3c33032
Revises: 
Create Date: 2025-05-13 23:10:45.694246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22feb3c33032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('sesso', sa.String(length=1), nullable=True))
    
    # Aggiorna i record esistenti impostando il sesso predefinito a 'M'
    op.execute("UPDATE guests SET sesso = 'M' WHERE sesso IS NULL")
    
    # Rendi la colonna NOT NULL dopo aver popolato i dati
    op.alter_column('guests', 'sesso', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('sesso')

    # ### end Alembic commands ###
