"""Add provincia_nascita field

Revision ID: 915621bc8a5f
Revises: 22feb3c33032
Create Date: 2025-05-13 23:19:26.992447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915621bc8a5f'
down_revision = '22feb3c33032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia_nascita', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('provincia_nascita')

    # ### end Alembic commands ###
